"""create prices table

Revision ID: f03740f9b1fd
Revises:
Create Date: 2026-02-05 18:15:54.704638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f03740f9b1fd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prices_ticker"), "prices", ["ticker"], unique=False
    )
    op.create_index(
        op.f("ix_prices_timestamp"), "prices", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prices_timestamp"), table_name="prices")
    op.drop_index(op.f("ix_prices_ticker"), table_name="prices")
    op.drop_table("prices")
    # ### end Alembic commands ###
